#!/usr/bin/env python
import sys
sys.path.insert(0, '')
from twisted.internet import reactor
from ayps import ayps
shell = ayps.Controller(stop_reactor_on_quit=True)
shell.startService()
reactor.run()
